name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy from'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          CI: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
